# Generated by Django 4.2 on 2024-10-24 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booktags',
            name='book',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='booktags',
            name='tag',
            field=models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='books.tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(db_column='AuthorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(db_column='CoverID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.cover', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(db_column='EditorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.editor', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.ForeignKey(db_column='FormatID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.format', verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.ForeignKey(db_column='PlaceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.place', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='book',
            name='seria',
            field=models.ForeignKey(db_column='SeriaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.seria', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', through='books.BookTags', to='books.tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='theme',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.theme', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(db_column='TypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.type', verbose_name='Тип книги'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('parent', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='booktags',
            unique_together={('book', 'tag')},
        ),
    ]
